### ISSUE TITLE
Storage nodes can have negative power

### ISSUE THREAD

**Issue by cyian-1756** [gdelazzari/tech_api#10]
It's possible for storage nodes to have their power level go into the negative, wouldn't it make more sense to them never go below 0?

**Comment by gdelazzari** [comment]
Sure, just curious: how did you get negative power?

**Comment by cyian-1756** [comment]
I had a user that always returned `2, 2, 2`

**Comment by gdelazzari** [comment]
Well that makes sense. In fact it's up to who implements a device to ensure the device doesn't use any more power than what's available, that's why there's an "available" parameter passed to the callback. I think I didn't include checks in the API just for performance reasons, but I may evaluate adding them.

**Comment by gdelazzari** [comment]
Related to #11
