### ISSUE TITLE
User callback firing every tick, no matter what is returned

### ISSUE THREAD

**Issue by cyian-1756** [gdelazzari/tech_api#11]
I made a user

```
tech_api.energy.register_device("itest2:quarry", "default", {
    type = 'user',
    max_rate = 2,
    linkable_faces = {'back', 'top', 'left', 'right', 'bottom'},
    callback = function(pos, dtime, available)
        minetest.chat_send_all("Call back")
        return 2, 2, 200
  end
})
```

And no matter what I return last (including -1) the call back runs every tick

**Comment by gdelazzari** [comment]
It's working as expected. The callback is firing every tick because you're always consuming 2 EU/t while you probably have no one providing that amount of power in the network. The API, as soon as it detects that there's no more enough energy available, calls you back, no matter what callback timer you have, to tell you (through "available") that you no more have 2 EU/t available for usage, and then the device must adhere to that and return a usage of 0 (or anything that's less or equal than what's available). If you won't stop using the power you don't have then the API will keep calling you back expecting you to stop. That's also what probably caused negative values in the storage devices.

I could add a check in the API to enforce users not to drain more energy than what's available, but then I think it wouldn't be clear in the devices implementations how much the device is actually consuming. What I mean is that, by leaving this aspect to the device implementation, it's more explicit. You should implement the callback something like this:

```lua
callback = function(pos, dtime, available)
  local can_consume = math.min(available, max_I_can_consume)
  -- do stuff depending on can_consume being enough for the device or not
  -- ...

  -- return telling the API what the device consumed, which must be less or equal to "available",
  -- as calculated with math.min at the beginning
  return 2, can_consume, 20
end
```

Then you can do advanced stuff. For example, if your machine can't work with less than, let's say, 10 EU/t (but can work at a varying speed between 10 and 50 EU/s) you'll have an `if can_consume >= 10 then` that fires when there's enough power, and at the end you'll return `can_consume` as the consumed energy. If, instead, you got less than 10, you skip doing any work and you return 0 power consumed to the API, even if 8 EU/t were available, for instance.

**Comment by gdelazzari** [comment]
You should see that by attaching a provider (that produces at least 2 EU/t) to the network or by changing the return parameters to something like `2, 0, 200` the callback will fire with the right timing. Also keep in mind the first parameter, which is the energy request. The API uses that to efficiently move energy around and an appropriate value must be returned. Basically, if you have a machine that always does work (from the moment you connect it to the moment you disconnect it) you'll have a fixed energy request, since you're always doing the same thing and you would like to have that amount of EU/t all the time (an always-on lamp, for instance). If the lamp was on/off switchable, instead, the energy request when the lamp is on would be of *x* EU/t, while being 0 when the lamp is switched off. The same thing goes for a furnace (requesting energy when there's an item ready to be cooked in it or requesting 0 when idle/having nothing to do). Then you can manage what the energy API gives you as I explained in the above comment (by dealing with `available` and the second return parameter, which is the energy you are actually consuming)

**Comment by cyian-1756** [comment]
Thanks for explaining that

**Comment by cyian-1756** [comment]
@gdelazzari 

I've changed my code to 

```
tech_api.energy.register_device("itest2:quarry", "default", {
    type = 'user',
    max_rate = 2,
    linkable_faces = {'back', 'top', 'left', 'right', 'bottom'},
    callback = function(pos, dtime, available)
        local can_consume = math.min(available, 2)
        if can_consume >= 2 then
            minetest.chat_send_all("test")
            return 2, can_consume, 60
        else
            return 2, 0, 60
        end
  end
})
```

And now the callback only fires every 60 ticks (and I get the chat message), but the node drains power from the storage node at a rate of 2 ever tick after the first call back fires (And no chat message fires)

Sorry if I'm missing something obvious here

Edit: The storage node is attached to a provider providing 5 EU/t

**Comment by gdelazzari** [comment]
Uhm, yeah. That's the expected behavior. Come on gitter.im so I can help you better understand
